spring:
  application:
    name: devlog-backend
  profiles:
    active: local

  jpa:
    open-in-view: false
  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: local

  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    sql: error

jwt:
  secret: secret